### ISSUE TITLE
Checklist for when a new project goes live/is transferred

### ISSUE THREAD

**Issue by Tuxified** [kabisa/launch-base#21]
We need a checklist to verify a project is ready to go live/ be transferred (in case of web app) to us.
This is a preliminary list, we need to investigate/add more items.

- [ ] verify mail can be sent
- [ ] have /ping endpoint + monitoring in place
- [ ] do a stress/load test
- [ ] implement continuous/auto deployment
- [ ] arrange enough disk space/S3

what else?
